apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-problem-detector
spec:
  template:
    metadata:
      labels:
        app: node-problem-detector
    spec:
      containers:
      - name: node-problem-detector
        command:
        - /node-problem-detector
        - --logtostderr=true
        - --system-log-monitors=/config/kernel-monitor.json
        - --custom-plugin-monitors=/config/custom-plugin-monitor.json
        #- --system-log-monitors=/config/kernel-monitor.json,/config/kernel-monitor-filelog.json,/config/docker-monitor.json,/config/docker-monitor-filelog.json
        image: tonychengtw/node-problem-detector1:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: log
          mountPath: /var/log/journal
          readOnly: true
        - name: kmsg
          mountPath: /dev/kmsg
          readOnly: true
        # Make sure node problem detector is in the same timezone
        # with the host.
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        #- name: plugin
        #  mountPath: /config/plugin
        #  readOnly: true
        #- name: config
        #  mountPath: /config
        #  readOnly: true
      volumes:
      - name: log
        # Config `log` to your system log directory
        hostPath:
          path: /var/log/
      - name: kmsg
        hostPath:
          path: /dev/kmsg
      - name: localtime
        hostPath:
          path: /etc/localtime
      #- name: plugin
        #hostPath:
        #  path: /root/node-problem-detector/config/plugin
      - name: config
        #hostPath:
        #  path: /root/node-problem-detector/config
        #configMap:
        #  name: node-problem-detector-config
